THRESHOLD_RAIN_SLOW_DRIVER_SPEED = 50
THRESHOLD_DRY_SLOW_DRIVER_SPEED = 80
FREQUENCY_NR_FOR_SLOW_DRIVER = 3
THRESHOLD_OVERTAKE_FOR_INTERVAL_WITH_DRS = 0.6
THRESHOLD_OVERTAKE_FOR_INTERVAL_WITHOUT_DRS = 0.3
